### ISSUE TITLE
Doesn't support 💯 emoji?

### ISSUE THREAD

**Issue by csampersand** [sindresorhus/emoj#10]
It seems like no combination of searches can find the 💯 (hundred) emoji.

**Comment by sindresorhus** [comment]
What it finds is based on actual usage on the web. I guess very few uses that emoji.

This is a good read on how it works: http://getdango.com/emoji-and-deep-learning.html

**Comment by chriscorwin** [comment]
Came here to file this issue.

` ¯\_(ツ)_/¯ `
