### ISSUE TITLE
not rendering emojis (mac)

### ISSUE THREAD

**Issue by Ghostavio** [sindresorhus/emoj#12]
Using iTerm 2:
![screen recording 2016-09-08 at 11 10 am](https://cloud.githubusercontent.com/assets/377506/18343785/0e98ff00-75b5-11e6-8010-8a7ca36d0e65.gif)

**Comment by sindresorhus** [comment]
Are you connected to the internet?

**Comment by Ghostavio** [comment]
yes

**Comment by sindresorhus** [comment]
The endpoint seems to be down: http://emoji.getdango.com/api/emoji?q=horse

**Comment by Ghostavio** [comment]
ah, ok

**Comment by Ghostavio** [comment]
maybe a nice error message would be nice tho 😄

**Comment by Ghostavio** [comment]
also it seems their api is not free http://getdango.com/api/
