### ISSUE TITLE
Add snapcraft.yaml file

### ISSUE THREAD

**Issue by popey** [sindresorhus/emoj#13]
Today I created a snap of emoj and this PR will contain a snapcraft.yaml to enable building of an emoj snap. I've tested the snap to make sure it works as expected, and find no issues so far.

I'd love to hear if you are generally interested in your software being available as a snap and if you could imagine shipping the snapcraft.yaml file in your source repository for easier publishing.

**Background info**

If you haven't heard of snaps yet, they are self-contained apps, which can be used on a [multitude of Linux](https://snapcraft.io/) systems. Via `seccomp`, `apparmor` and other Linux security features, they provide great security for users, uploads to the store are available within seconds and you have
full control over your relevant stack.

Snaps can be installed by millions of users: Ubuntu 16.04 LTS and later have snapd installed by default and many other Linux distributions, like Arch, Debian, Gentoo, Fedora, openSUSE, OpenEmbedded, Yocto and OpenWRT made snapd (which powers the snap experience) available as well.

**Publishing**

Uploading to the store can be done via the command line and there are multiple release channels available, so users can choose between for example stable, beta and alpha releases. You could even hook up snapcraft upload with Travis to auto-publish release tags or nightly builds. The process for this is very simple:

Once:
 * Register an account at http://myapps.developer.ubuntu.com/
 * Run `snapcraft login`
 * Run `snapcraft register emjo`
 * `snapcraft push emoj_<version>.snap --release=beta`

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/emoj/pull/14#issuecomment-249374404
