### ISSUE TITLE
Update to unicode 9.0 

### ISSUE THREAD

**Issue by apertureless** [sindresorhus/emoj#16]
The new emojis from [unicode 9](http://emojipedia.org/unicode-9.0/) / [emoji v3](http://emojipedia.org/emoji-3.0/) are missing, like 🤢

**Comment by sindresorhus** [comment]
From the readme:

> Uses the API from this great article on [Emoji & Deep Learning](http://getdango.com/emoji-and-deep-learning.html).
> Check out the [Dango app](http://getdango.com) if you want something like this on your phone.

I don't control the API. They've just been nice enough to let me use it.

I would suggest you email them about it: `hi@getdango.com`.
