### ISSUE TITLE
Please check out emoji-finder

### ISSUE THREAD

**Issue by dematerializer** [sindresorhus/emoj#17]
Hey Sindre!

I really love emoj. So much that I got inspired to start writing my own clone of it. As it evolved now I think it has reached a point where it turns out to be more than just a clone, rather like a successor to emoj. Please check out https://github.com/dematerializer/emoji-finder and tell me what you think of it.

Many thanks!

- Andy

**Comment by sindresorhus** [comment]
Looks like a good alternative. Nice work. I don't really see how it's a successor though. It just has more features. I've intentionally kept this one simple.
