### ISSUE TITLE
HTTPError: Response code 504 (Gateway Timeout)

### ISSUE THREAD

**Issue by flexiondotorg** [sindresorhus/emoj#31]
It looks like [emoji.getdango.com](https://emoji.getdango.com/api/) now requires an authentication token:

```
{"message":"Missing Authentication Token"}
```

**Comment by sindresorhus** [comment]
Same as https://github.com/sindresorhus/alfred-emoj/issues/15#issuecomment-351225176 It mostly works, but can be unreliably at times.
