### ISSUE TITLE
Dango API seems to be paid.

### ISSUE THREAD

**Issue by ShivanshuKantPrasad** [sindresorhus/emoj#35]
How does this app use Dango API. Dango API seems to be paid and it seems you have to have  a license from this [Dango API](https://getdango.com/api/) page.
How are you using the dango api in this project? Are there special permissions for Open Source Project.

**Comment by sindresorhus** [comment]
We're not using the official API. The API we're using was just a demo for an article they published. It works, but it doesn't scale. We've been allowed to use it for this specific tool.

**Comment by ShivanshuKantPrasad** [comment]
Okay.
