### ISSUE TITLE
Idea: Add option to output github markdown emoji

### ISSUE THREAD

**Issue by pixelbrackets** [sindresorhus/emoj#36]
I would be cool to have an option to output the emoji as »[github markdown string](https://gist.github.com/rxaviers/7360908   )«, e.g. 

```bash
~$ emoj -m smile
:blush: 😊 :relaxed: ☺️ :grinning: 😄
```

A user may use this to add emoj to commits or messages without nativ emoji support.

**Comment by sindresorhus** [comment]
Sorry, I don't really see the point of this. Emoji support is everywhere.
