### ISSUE TITLE
[Request] drool → 🤤

### ISSUE THREAD

**Issue by mesqueeb** [sindresorhus/emoj#38]
With the current version if I search for `drool` it does not find the drool face: 🤤

Only when I search for `drooling` it will find it.

I'd like to request that 🤤 shows up with just `drool`. Is this possible?

Is it related to fuzzy text search?

**Comment by sindresorhus** [comment]
We currently use an API to get the emojis, so we don't control the results. We have considered mixing it with local results (https://github.com/sindresorhus/emoj/issues/30), which would probably resolve this.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/emoj/commit/7de37c4f493c3750ca0e94adfbaa9f2419a9d9e1.
