### ISSUE TITLE
Skin tone

### ISSUE THREAD

**Issue by vhmth** [sindresorhus/emoj#4]
I always use skin tone 5 (well that's what Slack calls it anyway) because it closely lines up with my skin color. :-) Would love a way to specify that as an arg.

**Comment by sindresorhus** [comment]
👍 I'm thinking a CLI flag like `emoj --skin-tone=3`. For the interactive search I could add the ability to use keyboard arrow up/down to select skin tone. We could even save your last choice so you don't have to pick it each time. What do you think?

What I need to figure out is how to detect what emojis have support for skin tone modifiers. @mathiasbynens Do you happen to have a module for that?

**Comment by zwacky** [comment]
might be cool to have a default options like `emoj set skin-tone=3` so it applies it everytime. also having `--skin-tone=3` at hand would be great for single commands.

**Comment by mathiasbynens** [comment]
> What I need to figure out is how to detect what emojis have support for skin tone modifiers. @mathiasbynens Do you happen to have a module for that?

https://github.com/mathiasbynens/unicode-emoji-modifier-base

**Comment by jdalton** [comment]
Maybe pressing tab or something could cycle through modifiers.

**Comment by vhmth** [comment]
Up/down would be perfect. In https://github.com/sindresorhus/emoj/issues/2, Matchai said that clicking a number would "select" an emoji, so up/down could cycle through skin tones if they're available. I think supporting that and the arg would both be useful, but I actually see myself using the scheme of select number + up/down more.

**Comment by lukeed** [comment]
A combination of @zwacky and @vhmth's ideas would be perfect, imo.

Set global default with the `--skin-tone` flag. Applicable emojis appear as such, initially.

If one were to want a different tone for a specific emoji, "select" the emoji (by order position) and cycle thru available tones with <kbd>UP</kbd>/<kbd>DOWN</kbd> arrows.

Selecting this new emoji::tone combination should be saved in memory.

```
emoj --skin-tone=2
emoj 'hand'
```
<kbd>2</kbd>, <kbd>DOWN</kbd>, <kbd>SUPER</kbd> + <kbd>C</kbd>

<kbd>DOWN</kbd> = darker? Tone selection would now be `3`

**Comment by sindresorhus** [comment]
@mathiasbynens Awesome! :)

**Comment by sindresorhus** [comment]
I would prefer something simple. The <kbd>Tab</kbd> key to cycle through skin tones sounds better and I don't think you'd need to go up and down a lot. I also think it should change all of them. I don't see the use-case of individually changing the skin tone.

So my proposal:

- `--skin-tone=5` to set the skin tone. It's persisted and used in both interactive `$ emoj` and non-interactive `$ emoj 'i love unicorns'`
- In interactive mode, you can also cycle through skin tones with <kbd>Tab</kbd> for all the emoji results. It's not persisted.

**Comment by sindresorhus** [comment]
Any thoughts on my proposal?

I've made a [`skin-tone`](https://github.com/sindresorhus/skin-tone) module to make this feature easier to implement. Could use some feedback on that module (especially from @mathiasbynens).

**Comment by lukeed** [comment]
I'd still prefer <kbd>UP</kbd> and <kbd>DOWN</kbd> so that I don't have to press <kbd>Tab</kbd> 4 times to loop from 3 back to 2.

The rest of your proposal is spot on imo.

**Comment by vhmth** [comment]
Agreed that up/down is much more preferable. I actually hate that I can't do that in Slack. @sindresorhus go ahead and try it in slack where you start the emoji with `:` and try to get to a skin tone by tabbing through. It's a huge PITA. :-P

**Comment by sindresorhus** [comment]
Alright. Up/Down then.

**Comment by JonnyBel** [comment]
Hi, I made a pull request with a proposed solution for this issue, #19 

It is my very first pull request ever, so I'd greatly appreciate feedback :raised_hands:
