### ISSUE TITLE
RequestError: certificate has expired

### ISSUE THREAD

**Issue by mesqueeb** [sindresorhus/emoj#41]
When I tried alfred and typed `emoj laugh` today, I got:

> RequestError: certificate has expired
    at ClientRequest.req.once.err (/usr/local/lib/node_modules/alfred-emoj/node_modules/got/index.js:182:22)

**Comment by danielfilho** [comment]
this is an issue with `emoji.getdango.com/api/emoji`, unfortunately :/

**Comment by mesqueeb** [comment]
There must be some solution!! I'd hate this to be the end of the `emoj` Alfred extension. 😭😭😭😭😭

**Comment by danielfilho** [comment]
I've sent a message to them. Hopefully they'll get it sorted.

**Comment by danielfilho** [comment]
This was fixed by `getdango.com` fixed and can be closed. Same for #42.

/cc @sindresorhus
