### ISSUE TITLE
RequestError: certificate has expired

### ISSUE THREAD

**Issue by arnauldb** [sindresorhus/emoj#42]
Hello,

On Linux Mint 18.3 Sylvia.

I used emoj for a while but since yesterday I have this message:

> $  emoj cat
> RequestError: certificate has expired
>     at ClientRequest.req.once.err (/snap/emoj/53/lib/node_modules/emoj/node_modules/got/index.js:111:21)
>     at Object.onceWrapper (events.js:315:30)
>     at emitOne (events.js:116:13)
>     at ClientRequest.emit (events.js:211:7)
>     at TLSSocket.socketErrorListener (_http_client.js:387:9)
>     at emitOne (events.js:116:13)
>     at TLSSocket.emit (events.js:211:7)
>     at emitErrorNT (internal/streams/destroy.js:64:8)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)

Any suggestions?

Thank you.

**Comment by danielfilho** [comment]
Duplicated #41
