### ISSUE TITLE
`emoj` API is down

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/emoj#49]
`http://emoji.getdango.com/api/emoji` no longer goes anywhere. We might want to consider trying to get the [offline predictions SDK](http://getdango.com/api/#offline-predictions-sdk).

**Comment by sindresorhus** [comment]
The API goes down sometimes. Hopefully, it will come back. I doubt we can do the SDK as it's paid.

**Comment by Richienb** [comment]
Unfortunately, this was not actually the first occasion in which the API went down. It has been consistently down for months.

**Comment by Richienb** [comment]
It seems that Dango has disappeared for good. The website no longer exists and the app is no longer on Google Play.

**Comment by sindresorhus** [comment]
Yeah... Seems we need to take out the API calls and rely only on the emoji lib dependency.

**Comment by Richienb** [comment]
For posterity:

In 2012, Toronto-based company [Whirlscape](http://www.whirlscape.com/) was founded as a result of a [Y Combinator W14 seed investment](https://www.ycdb.co/company/whirlscape). Among its co-founders is [Severin Smith](http://www.smallbutdigital.com/about/) ([twitter](https://twitter.com/thesprky)).

In 2013, the company published [Minuum](http://minuum.com/), an Android and iOS predictive keyboard app that aimed to predict the text and emojis that a user wanted to type.

In 2014, the company published [Dango](https://web.archive.org/web/20200922082042/https://getdango.com/), an Android app that provided a emoji suggestions widget that appeared when the user input text. The app was removed from Google Play at some point between December 17,  2019 and June 10, 2021; and the website changed owners on May 27, 2021 after being down since at least December 2020.
